import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import App from "./app";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body style={{ backgroundColor: '#fdd9e5' }} className={`${inter.className} min-h-screen`}>
        <App>{children}</App>
      </body>
    </html>
  );
}
